### ISSUE TITLE
Access Denied errors in download scripts for GPT-2

### ISSUE THREAD

**Issue by lwestfall** [losttech/Gradient-Samples#12]
OpenAI has moved its datasets to Azure, the google cloud URLs are no longer working for downloading the GPT-2 datasets.

Lines that need to be updated:

https://github.com/losttech/Gradient-Samples/blob/3b8d568d787b1a8e02d0bc1dd546906c8aba6ffe/v1/GPT-2/download_model.sh#L16

https://github.com/losttech/Gradient-Samples/blob/3b8d568d787b1a8e02d0bc1dd546906c8aba6ffe/v1/GPT-2/download_model.ps1#L12

`https://storage.googleapis.com/gpt-2/models/$fetch` should be `https://openaipublic.azureedge.net/gpt-2/models/$fetch`. 

See https://github.com/openai/gpt-2-output-dataset/commit/2c102400c7e4e698acd3f0e51d3b6cf1c637c0fe

**Comment by lostmsu** [comment]
@lwestfall thanks for pointing this out. We actually moved GPT into [its own repository](https://github.com/losttech/GPT). Forgot to update the download URL here.

**Comment by lostmsu** [comment]
Mentioned that GPT has been moved in README.
